### ISSUE TITLE
Sketch Hardware

### ISSUE THREAD

**Issue by Defragster** [sparkfun/MEMS_Mic_Breakout-ADMP401#1]
What hardware does the example sketch write to?

**Comment by ToniCorinne** [comment]
This sketch was written for use on an Arduino. You can see our example circuit [here](https://www.youtube.com/watch?v=0jW1Kuw79hA), using a Redboard, [LED RingCoder Breakout](https://www.sparkfun.com/products/11040), and one of the MEMS breakouts.
